language: java
jdk: 
 - openjdk8

before_install:
 - cd ProtoBot
 - pwd
 - ls -la
 - chmod +x gradlew

script:
 - ./gradlew build
 - ./gradlew jacocoTestReport

after_success:
 - bash <(curl -s https://codecov.io/bash)
