language: java
jdk: 
 - openjdk8

before_install:
 - cd BasicMeleeBot
 - pwd
 - ls -la
 - chmod +x gradlew

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  
script:
 - ./gradlew build
 - ./gradlew jacocoTestReport
