language: java
jdk: 
 - openjdk8

env:
  global:
    - CC_TEST_REPORTER_ID=b729d4f168fd77159b249e93931ad1277863e15ace2d62318c5f7b8c30c51d69
    
before_install:
 - cd BasicMeleeBot
 - pwd
 - ls -la
 - chmod +x gradlew
 - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
 - chmod +x ./cc-test-reporter
 - ./cc-test-reporter before-build
  
script:
 - ./gradlew build
 - ./gradlew jacocoTestReport

after_script:
 - JACOCO_SOURCE_PATH=src/main/java ./cc-test-reporter format-coverage build/customJacocoReportDir/test/jacocoTestReport.xml --input-type jacoco
 - ./cc-test-reporter upload-coverage --add-prefix /BasicMeleeBot
